### ISSUE TITLE
Create Typescript UI module in presentation layer

### ISSUE THREAD

**Issue by mchadwickDD** [nico-guba/deloitte-advantage#6]

**Comment by mchadwickDD** [comment]
It's been more exciting than it should have been, but here we are.  The typescript project that currently resides in `layers/presentation/ui` now gets deployed by Amplify as part of the `amplify.yml` file, with the static files being removed from `layers/presentation/src/main/resources`.

**Comment by nico-guba** [comment]
Is this still open?  Given your successful deployment to Amplify, I would argue we can set this aside now.  Might need a better title though.  Maybe along the lines "ensure we can deploy frontend to AWS"?
